require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - config/**/*
    - config.ru
    - Rakefile
    - Gemfile
  DisplayCopNames: true
  NewCops: enable

##################### Style ##################################
# Rails用の設定を有効化
Rails:
  Enabled: true

# Metrics
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

# Layout
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: normal

# Style
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: compact
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/DoubleNegation:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

# Rspec
RSpec/ContextWording:
  Enabled: false
RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Gemfile
Bundler/OrderedGems:
  Enabled: false
